backend:
  name: git-gateway
  branch: feat--netlifycms
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "/content/en/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}.md" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "rls"
    label: "Rules"
    folder: "/content/rls"
    create: false
    slug: "{{iso}}.md"
    fields:
      - {label: "State", name: "state", widget: "string"}
      - {label: "ISO Code", name: "iso", widget: "string"}
      - {label: "Never Resideds are allowed to register", name: "allowsNeverResided", widget: "boolean"}
