backend:
  name: git-gateway
  branch: feat--netlifycms
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "/content/en/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}.md" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
